/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DomainDetail: typeof import('./src/components/DomainDetail.vue')['default']
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
    Layout: typeof import('./src/components/Layout.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/components/Switch.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  }
}
